"""
The plugin's telemetry registry: every span, attribute and metric the
exporter emits about itself, in datasette's registry classes.

The names themselves are plain strings defined in ``exporter.py`` (which must
stay datasette-free); this module wraps them so datasette's conformance
helpers (``datasette.telemetry_testing.assert_spans_conform`` and friends) can
check that what is emitted matches what is documented. Nothing at runtime
imports this module - it is for tests and documentation.
"""

from datasette.telemetry_registry import (
    COUNTER,
    HISTOGRAM,
    Attribute,
    MetricName,
    SpanName,
)

from . import exporter

TRIGGER = Attribute(
    exporter.ATTR_TRIGGER,
    "Why the file rolled: the flush interval elapsed, ``max_buffer_spans`` "
    "accumulated, an explicit ``force_flush()``, or process shutdown.",
    values=exporter.TRIGGERS,
)
FORMAT = Attribute(
    exporter.ATTR_FORMAT,
    "The file encoding, ``ndjson`` or ``parquet``.",
    values=tuple(exporter.FORMATS),
)
STORE = Attribute(
    exporter.ATTR_STORE,
    "Where the file went: ``file`` for a local directory, otherwise the "
    "``url:`` scheme (``s3``, ``gs``, ``az``, ...).",
)
FILE_KEY = Attribute(
    exporter.ATTR_FILE_KEY,
    "The file's key under the path or URL prefix - generated by the "
    "exporter, never user input.",
)
FILE_SIZE = Attribute(
    exporter.ATTR_FILE_SIZE,
    "Encoded (compressed) size of the file in bytes; the bytes handed to the "
    "store. Absent when encoding itself failed.",
    optional=True,
)
SPANS = Attribute(exporter.ATTR_SPANS, "Number of span records in the file.")
ENCODE_NS = Attribute(
    exporter.ATTR_ENCODE_NS,
    "Nanoseconds spent encoding; the span's duration minus this is the "
    "store write. Absent when encoding itself failed.",
    optional=True,
)
ERROR_TYPE = Attribute(
    exporter.ATTR_ERROR_TYPE,
    "Exception class name when the write failed (the batch was dropped). "
    "The span's status is ``ERROR`` with the exception message.",
    optional=True,
)

FLUSH = SpanName(
    exporter.FLUSH_SPAN,
    "One telemetry file written (or attempted). A root span in the "
    "exporter's own scope, recorded in the *next* file - a buffer holding "
    "only these never rolls a file of its own.",
    (TRIGGER, FORMAT, STORE, FILE_KEY, FILE_SIZE, SPANS, ENCODE_NS, ERROR_TYPE),
)

SPAN_NAMES = (FLUSH,)

M_FILE_SIZE = MetricName(
    exporter.METRIC_FILE_SIZE,
    HISTOGRAM,
    "By",
    "Encoded size of each telemetry file successfully written.",
    (FORMAT, STORE),
    buckets=exporter.FILE_SIZE_BUCKETS,
)
M_FILES = MetricName(
    exporter.METRIC_FILES,
    COUNTER,
    "{file}",
    "Telemetry files written or attempted; failures carry ``error.type``.",
    (FORMAT, STORE, ERROR_TYPE),
)

METRICS = (M_FILE_SIZE, M_FILES)
